name: Go Lint
permissions:
  contents: read
on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  lint:
    uses: grokify/.github/.github/workflows/go-lint.yaml@main
