name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  ci:
    uses: grokify/.github/.github/workflows/ts-ci.yaml@main

  lint:
    uses: grokify/.github/.github/workflows/ts-lint.yaml@main
